language: node_js
node_js:
- 10
cache:
  directories:
  - node_modules
jobs:
  include:
  - stage: test
    script:
    - npm run lint
    - npm run build
    - npm run test
    after_success: echo "test stage success"
  - stage: npm release
    if: tag IS present
    node_js: '10'
    script:
    - npm run lint
    - npm run build
    - npm run test
    - echo "Publishing to npm..."
    deploy:
      provider: npm
      skip_cleanup: true
      on:
        tags: true
      email: npm@nerdwallet.com
      api_key:
        secure: AlupdcHWvyKwh9Lm9p4BeXE30e3DXCxkmLz54N7ilOK9S66c6GugKg4GTp/JOvFrFfTZ5S8gGoBusUURJeAaGwYxGbYZXNuUK3c8i6mJi0+SpEeQnKyAsMOkQWf2fgyw+BtK4Zc9ZNpgLfHPWpXJybG9DG1L5ie7IBUbANUuqDPVuZxC+PSEhbPm9UbxqKNSH+QVxlaHxtsRgRjWUOCOO1jHa3J3PGw2OdvY9V8Ttd6pO0f4clR45C5LpGvdHTIIFn0iwn9SpNzFH87NrtQGSeliEJcYmbeZFpg2TIgC/pvdZAUmCCqmlPcwq3V5QptAtD5DO4geP8IDSXUOGbDYw9xYSdSSJ4l0Z5iRDqyCsVLJ+XVZkCcM1vDo/3GNFPbFv57TcBxrsOWvFl4t4/+4FKZAuG0O5na0bRgHT5spv02q6i+7IouQehdymtV83gFXZDaxkJH0w/c8VKvbw2up2bEVY/rMivdxMc9CSQZFgYNUV4dVBVyiExq+GPukrE4+7loB5qXTLMAzCpOh6FOrISpEvyHIgMlHsr3xE/SLeffmck8obz4ZpOFJYUCSdUNgvsj7gZjQYRESlvCojrOJd8EC0zdMwg7Rw95QV25N/UVO39cPxfG7Yv+eVmlKoNz9HbwBsRiPcvGVvHHu7czXmzetWnPU/HaNWEExtMxcnKc=
