language: node_js
node_js:
- 10
cache:
  directories:
  - node_modules
jobs:
  include:
  - stage: test
    script:
    - npm run lint
    - npm run build
    - npm run test
    after_success: echo "test stage success"
  - stage: npm release
    if: tag IS present
    node_js: '10'
    script:
    - npm run lint
    - npm run build
    - npm run test
    - echo "Publishing to npm..."
    deploy:
      provider: npm
      skip_cleanup: true
      on:
        tags: true
      email: npm@nerdwallet.com
      api_key:
        secure: XWpG5RzTd8EfpU/OVPTHSGoFdaRSvB/qIr8yhwlOaLQVLjP0CI7b/D4hC4I7nU1uLsOqqcNyB+fZOk9qwuWxUpygb246ofemvEbK25BPQUzdBajnVI4gb3W9JL53xq/T/w200/7/88obJGOIlq7e7UtJx81ZGBBp6c8gEifOfsYMmFfaHg8WXqnfpvvFKmzK/aVRzq1RJGayN0Axzq+NAbcp54748/oDkO4QAMJqRTU80PtLj5bPQjF7LxRJLToJQgpSghiBm0Lk0XRvSHIgV7O+4IyUu5rigVkOjQh1L9neCyDsWdVK3LCVxgeCWx8hRoGC8iHSh/hDK+eP2TMPqrs0RhGBXzhrwO2xv1gCDtDJ2kJWh/AsxJKq/6y+tA7ODDb6jrRFBfgrlIiislOontApjCchwAzwhiG7mFpu/IQgYvT5z7Zr1yOY/tq7qu7ftiLyHAp/SeYx/6tkxFKW//UiYWJULk7fCOQ5vnRhQTDy9We4BmUqmk4a75HxwUlPsSAMAE0H22O8hwsMs+d2FtGH55GCS5mJVjcYq9LHju1+JENlc/Z1al6CsbbrpU++J20t/gOsug+5wIMyTn7vf7dWEO1c/JhGuyG3s87Hfr0Qq8f4W7gJRcbzqS9ZU5zjsNmnwAn10oMAywhfDt3Qq3Km1JTx9+f5KtdjK2Wjcak=
